# Generated by Django 2.0.3 on 2018-03-18 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0009_auto_20180312_1537'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickevent',
            name='kirr_url',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='shortener.KirrURL'),
        ),
    ]
